-- Preguntas DEMO (generado por tools/generate-seed.js — no editar a mano).
-- Ejecutar después de schema.sql. Se puede repetir: actualiza las preguntas existentes.
insert into public.questions (id, category, type, question, options, context, explanation, correct_answer) values
  (1, 'KYOTO', 'multiple_choice', '¿Cuál es el objetivo principal del Protocolo de Kioto?', '["Proteger los humedales","Reducir las emisiones de gases de efecto invernadero","Regular el comercio de fauna silvestre","Controlar los residuos peligrosos"]'::jsonb, null, null, 1),
  (2, 'KYOTO', 'true_false', 'El Protocolo de Kioto fijó metas vinculantes de reducción de emisiones para los países desarrollados.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (3, 'ROTTERDAM', 'multiple_choice', '¿Qué mecanismo central aplica el Convenio de Rotterdam?', '["Subasta de bonos de carbono","Consentimiento fundamentado previo para ciertos químicos y plaguicidas","Inventario de humedales","Prohibición total del transporte marítimo"]'::jsonb, null, null, 1),
  (4, 'ROTTERDAM', 'situational', 'Una empresa quiere exportar un plaguicida incluido en el Convenio de Rotterdam. ¿Qué debe verificar primero?', '["Que el país importador haya dado su consentimiento informado","Que el producto tenga empaque reciclable","Que el precio sea competitivo","Que el envío se haga en temporada seca"]'::jsonb, null, null, 0),
  (5, 'ESCAZU', 'multiple_choice', 'El Acuerdo de Escazú garantiza principalmente el acceso a…', '["Créditos de carbono","Información, participación pública y justicia en asuntos ambientales","Energía renovable subsidiada","Tecnología de reciclaje"]'::jsonb, null, null, 1),
  (6, 'ESCAZU', 'true_false', 'El Acuerdo de Escazú es un tratado regional de América Latina y el Caribe.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (7, 'BASILEA', 'multiple_choice', '¿Qué regula principalmente el Convenio de Basilea?', '["Comercio de especies amenazadas","Movimiento transfronterizo de residuos peligrosos y su eliminación","Protección de la capa de ozono","Conservación de humedales"]'::jsonb, null, null, 1),
  (8, 'BASILEA', 'situational', 'Una empresa necesita transportar residuos peligrosos a otro país. ¿Qué aspecto debe considerar prioritariamente?', '["El menor costo de flete","La notificación y el consentimiento previo de los países implicados","El color de los contenedores","La rapidez de la entrega"]'::jsonb, null, null, 1),
  (9, 'CITES', 'multiple_choice', '¿Qué protege la Convención CITES?', '["Especies de fauna y flora silvestres frente al comercio internacional no sostenible","Los océanos de la contaminación por plásticos","La calidad del aire urbano","Los suelos agrícolas"]'::jsonb, null, null, 0),
  (10, 'CITES', 'error_identification', 'Un estudiante afirma: "CITES controla el transporte de residuos peligrosos entre países". ¿Cuál es el error?', '["Ninguno, la afirmación es correcta","Eso corresponde al Convenio de Basilea; CITES regula el comercio de especies","CITES solo regula la pesca","CITES solo aplica dentro de un mismo país"]'::jsonb, null, null, 1),
  (11, 'RAMSAR', 'multiple_choice', 'La Convención de Ramsar se enfoca en la conservación y el uso racional de…', '["Bosques tropicales","Humedales","Glaciares","Desiertos"]'::jsonb, null, null, 1),
  (12, 'RAMSAR', 'true_false', 'Ramsar promueve el uso racional de los humedales de importancia internacional.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (13, 'PARIS', 'multiple_choice', 'El Acuerdo de París busca limitar el aumento de la temperatura global muy por debajo de…', '["1 °C","2 °C","4 °C","5 °C"]'::jsonb, null, null, 1),
  (14, 'PARIS', 'multiple_choice', '¿Cómo se llaman los compromisos climáticos que cada país define en el Acuerdo de París?', '["Contribuciones determinadas a nivel nacional (NDC)","Certificados de reciclaje","Cuotas de pesca","Planes de ordenamiento portuario"]'::jsonb, null, null, 0),
  (15, 'MONTREAL', 'multiple_choice', 'El Protocolo de Montreal elimina progresivamente sustancias que…', '["Contaminan los ríos","Agotan la capa de ozono","Generan residuos electrónicos","Amenazan a los humedales"]'::jsonb, null, null, 1),
  (16, 'MONTREAL', 'interpretation', '¿Qué conclusión es la más adecuada?', '["Los acuerdos ambientales multilaterales no tienen efecto","La cooperación internacional puede lograr resultados ambientales medibles","El problema del ozono nunca existió","Solo la tecnología resuelve problemas ambientales"]'::jsonb, 'Tras la entrada en vigor del Protocolo de Montreal, la producción de CFC se eliminó de forma progresiva y la capa de ozono muestra señales de recuperación.', null, 1),
  (17, 'GINEBRA', 'multiple_choice', 'El Convenio de Ginebra de 1979 trata sobre…', '["Contaminación atmosférica transfronteriza a gran distancia","Comercio de especies amenazadas","Residuos peligrosos","Pesca en alta mar"]'::jsonb, null, null, 0),
  (18, 'GINEBRA', 'true_false', 'La contaminación del aire puede cruzar fronteras y afectar a países distintos del que la emite.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (19, 'GOTHENBURG', 'multiple_choice', 'El Protocolo de Gotemburgo busca reducir…', '["La acidificación, la eutrofización y el ozono troposférico","La pesca ilegal","El tráfico de fauna","El uso de papel"]'::jsonb, null, null, 0),
  (20, 'GOTHENBURG', 'true_false', 'El Protocolo de Gotemburgo establece techos de emisión para contaminantes como SO₂, NOx y amoníaco.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (21, 'BRUNDTLAND', 'multiple_choice', 'Según el Informe Brundtland, el desarrollo sostenible es el que…', '["Maximiza el crecimiento económico sin límites","Satisface las necesidades presentes sin comprometer a las generaciones futuras","Prohíbe toda actividad industrial","Prioriza solo la conservación de especies"]'::jsonb, null, null, 1),
  (22, 'BRUNDTLAND', 'situational', 'Una empresa logística debe elegir entre ahorrar costos con rutas muy contaminantes o rediseñarlas para reducir emisiones. ¿Qué decisión se alinea con el desarrollo sostenible?', '["Mantener la ruta más contaminante","Rediseñar rutas equilibrando costo, ambiente y sociedad","Eliminar la distribución","Trasladar el problema a otro proveedor"]'::jsonb, null, null, 1),
  (23, 'EPI', 'multiple_choice', 'El Índice de Desempeño Ambiental (EPI) sirve para…', '["Clasificar a los países según su desempeño ambiental","Fijar el precio del carbono","Medir la velocidad del reciclaje","Autorizar la exportación de residuos"]'::jsonb, null, null, 0),
  (24, 'EPI', 'true_false', 'El EPI evalúa indicadores como la salud ambiental y la vitalidad de los ecosistemas.', '["Verdadero","Falso"]'::jsonb, null, null, 0)
on conflict (id) do update set
  category = excluded.category, type = excluded.type, question = excluded.question,
  options = excluded.options, context = excluded.context, explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
