-- Banco de preguntas (generado por tools/generate-seed.js desde js/questions.js — no editar a mano).
-- Ejecutar después de schema.sql. Se puede repetir: reemplaza el banco completo.
delete from public.questions where id not in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20);
insert into public.questions (id, category, type, question, options, context, explanation, correct_answer) values
  (1, 'BRUNDTLAND', 'multiple_choice', 'Una empresa quiere aumentar su producción rápidamente, pero para hacerlo tendría que agotar recursos naturales que serán necesarios en el futuro. ¿Qué elemento de esta decisión contradice el enfoque planteado por Brundtland?', '["Considerar las necesidades sociales","Proteger los recursos pensando en el futuro","Buscar mayor eficiencia productiva","Agotar los recursos para aumentar la producción"]'::jsonb, null, null, 3),
  (2, 'BRUNDTLAND', 'true_false', 'Para el enfoque de Brundtland, el desarrollo no debería basarse en una explotación ilimitada de los recursos naturales.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (3, 'KYOTO', 'multiple_choice', '¿En qué año entró en vigor el Protocolo de Kioto?', '["1992","1997","2005","2015"]'::jsonb, null, null, 2),
  (4, 'KYOTO', 'multiple_choice', '¿Cuál de las siguientes afirmaciones sobre Estados Unidos y el Protocolo de Kioto es correcta?', '["Estados Unidos firmó el protocolo, pero no lo ratificó.","Estados Unidos nunca firmó el protocolo.","Estados Unidos ratificó el protocolo en 2005.","Estados Unidos fue uno de los países que creó el Convenio de Ramsar."]'::jsonb, null, null, 0),
  (5, 'PARIS', 'multiple_choice', 'Además de las acciones para enfrentar el cambio climático, ¿qué elemento contempla el Acuerdo de París?', '["Comercio internacional de especies","Transporte transfronterizo de residuos","Protección exclusiva de humedales","Financiamiento climático"]'::jsonb, null, null, 3),
  (6, 'PARIS', 'true_false', 'El Acuerdo de París contempla aspectos relacionados con adaptación y resiliencia, además de las acciones de reducción de emisiones.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (7, 'CITES', 'multiple_choice', 'Un país desea solicitar cooperación internacional para controlar el comercio de una especie que ya regula dentro de su territorio. ¿Qué apéndice de CITES corresponde a esta situación?', '["Apéndice I","Apéndice III","Apéndice II","Ningún apéndice"]'::jsonb, null, null, 1),
  (8, 'CITES', 'error_identification', '¿Cuál de las siguientes afirmaciones sobre CITES es INCORRECTA?', '["Utiliza permisos y certificados en determinados casos.","Cuenta con diferentes apéndices para establecer niveles de regulación.","Prohíbe absolutamente todo comercio internacional de especies silvestres.","Busca controlar determinados casos de comercio internacional de fauna y flora silvestres."]'::jsonb, null, null, 2),
  (9, 'RAMSAR', 'multiple_choice', 'Una comunidad quiere aprovechar un humedal sin destruir sus características ecológicas. ¿Cuál de las siguientes decisiones se relaciona mejor con el principio de “uso racional” promovido por Ramsar?', '["Utilizar el humedal de manera sostenible conservando sus funciones ecológicas.","Drenar completamente el humedal.","Eliminar toda actividad humana sin excepción.","Convertir el humedal en una zona industrial."]'::jsonb, null, null, 0),
  (10, 'RAMSAR', 'true_false', 'El enfoque de Ramsar implica que los humedales deben permanecer completamente aislados de cualquier forma de uso humano.', '["Verdadero","Falso"]'::jsonb, null, null, 1),
  (11, 'BASILEA', 'multiple_choice', 'Antes de realizar determinados movimientos transfronterizos de residuos regulados por el Convenio de Basilea, ¿qué principio resulta fundamental?', '["Uso racional","Participación pública","Adaptación climática","Consentimiento fundamentado previo"]'::jsonb, null, null, 3),
  (12, 'BASILEA', 'error_identification', '¿Cuál de las siguientes relaciones es INCORRECTA?', '["Basilea → movimientos transfronterizos de residuos peligrosos","CITES → protección y comercio internacional de especies silvestres","Ramsar → comercio internacional de especies silvestres","Basilea → consentimiento fundamentado previo"]'::jsonb, null, null, 2),
  (13, 'GINEBRA', 'true_false', 'Los problemas relacionados con la lluvia ácida ayudaron a evidenciar la necesidad de cooperación internacional frente a la contaminación atmosférica que puede desplazarse entre países.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (14, 'GOTHENBURG', 'multiple_choice', 'Un programa ambiental establece límites para las emisiones de SO₂, NOx, compuestos orgánicos volátiles (COV) y NH₃. ¿Con qué instrumento se relaciona principalmente?', '["Acuerdo de París","Protocolo de Kioto","Protocolo de Gotemburgo","Convenio de Ramsar"]'::jsonb, null, null, 2),
  (15, 'GOTHENBURG', 'true_false', 'El Protocolo de Gotemburgo está relacionado exclusivamente con las emisiones de CO₂.', '["Verdadero","Falso"]'::jsonb, null, null, 1),
  (16, 'ESCAZU', 'multiple_choice', 'Una persona que defiende activamente el ambiente en su territorio recibe amenazas debido a su labor. ¿Qué aspecto relacionado con el Acuerdo de Escazú resulta especialmente pertinente?', '["Comercio internacional de especies","Gestión de humedales","Transporte de residuos peligrosos","Protección de personas defensoras del ambiente"]'::jsonb, null, null, 3),
  (17, 'EPI', 'multiple_choice', '¿Cuál de las siguientes afirmaciones describe correctamente la estructura del Índice de Desempeño Ambiental (EPI) presentada en el material?', '["Se publica anualmente y utiliza únicamente un indicador.","Se publica bienalmente y utiliza múltiples indicadores agrupados en categorías y objetivos.","Solo compara las emisiones de CO₂.","Mide exclusivamente la cantidad de residuos producidos."]'::jsonb, null, null, 1),
  (18, 'EPI', 'true_false', 'El Índice de Desempeño Ambiental (EPI) se publica de manera bienal.', '["Verdadero","Falso"]'::jsonb, null, null, 0),
  (19, 'INTEGRADORA', 'multiple_choice', '¿Cuál de las siguientes relaciones es CORRECTA?', '["Protocolo de Gotemburgo → límites de determinados contaminantes atmosféricos","Ramsar → comercio internacional de especies","CITES → conservación y uso racional de humedales","Basilea → protección de defensores ambientales"]'::jsonb, null, null, 0),
  (20, 'INTEGRADORA', 'error_identification', 'Una empresa está analizando diferentes instrumentos ambientales. ¿Cuál de las siguientes decisiones está MAL RELACIONADA?', '["Consultar Basilea antes de analizar determinados movimientos transfronterizos de residuos.","Consultar Escazú cuando exista participación y defensa de derechos ambientales.","Consultar Gotemburgo frente a determinados contaminantes atmosféricos.","Consultar CITES para establecer el uso racional de un humedal."]'::jsonb, null, null, 3)
on conflict (id) do update set
  category = excluded.category, type = excluded.type, question = excluded.question,
  options = excluded.options, context = excluded.context, explanation = excluded.explanation,
  correct_answer = excluded.correct_answer;
